name: Run YouTube Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  youtube_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YouTube Scraper with Username and Password
        run: |
          python youtube_meeting_map.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}  # Make sure your API key is set as a secret
          YT_USERNAME: ${{ secrets.YT_USERNAME }}  # Pass username secret
          YT_PASSWORD: ${{ secrets.YT_PASSWORD }}  # Pass password secret

      - name: Clean up
        run: |
          rm -f YOUTUBE_COOKIES.txt  # Optional: Clean up after the job finishes
