name: Run YouTube Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  youtube_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode cookies from GitHub secret
        run: |
          if [ -z "$YOUTUBE_COOKIES" ]; then
            echo "Error: YOUTUBE_COOKIES secret is not set or empty."
            exit 1
          fi
          echo "$YOUTUBE_COOKIES" | base64 --decode > YOUTUBE_COOKIES.txt

      - name: Debug Cookies File
        run: |
          echo "Contents of YOUTUBE_COOKIES.txt:"
          cat YOUTUBE_COOKIES.txt
          
      - name: Verify cookies file
        run: |
          if [ ! -s YOUTUBE_COOKIES.txt ]; then
            echo "Error: YOUTUBE_COOKIES.txt is empty or missing."
            exit 1
          fi

      - name: Run YouTube Scraper
        run: |
          python youtube_meeting_map.py || exit 1
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Clean up
        run: |
          rm YOUTUBE_COOKIES.txt
