name: YouTube Meeting Map

on:
  push:
    branches:
      - main

jobs:
  youtube-meeting-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install yt-dlp

    - name: Decode cookies file from GitHub Secrets
      run: |
        echo "${{ secrets.YOUTUBE_COOKIES }}" | base64 --decode > cookies.txt

    - name: Run YouTube scraper
      run: |
        python youtube_meeting_map.py
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Clean up
      run: rm cookies.txt
