name: Update Map

on:
  workflow_dispatch: # Allows manual triggering
  schedule:          # Optional: Schedule it (e.g., daily)
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python youtube_meeting_map.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all  # Tracks new, modified, and deleted files
          git commit -m "Update site content" || echo "No changes to commit"
          git push
        continue-on-error: true
