name: Run YouTube Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  youtube_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode cookies from GitHub secret
        run: |
          echo "$YOUTUBE_COOKIES" | base64 --decode > YOUTUBE_COOKIES.txt

      - name: Run YouTube Scraper
        run: |
          python youtube_meeting_map.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}  # Make sure your API key is set as a secret
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Clean up
        run: |
          rm YOUTUBE_COOKIES.txt  # Optional: Clean up after the job finishes
